#!/usr/bin/env python3
"""Conditional append-token distribution by cached-prefix size, per provider.

Populates ``tab:append_by_prefix`` (``src/05_LLMGeneration.tex``): for Claude and Codex, bin
every agent step by its cached-prefix length (``prefix_tokens``) and report the distribution of
the *newly appended* (uncached) tokens (``newly_append_tokens``) within each bin --- count, avg,
p50, p90, p99. This quantifies the scatter in ``fig:prefill_append_relationship``: appended
length is large only at cold start (no cache) and collapses to a few hundred tokens once a large
prefix accumulates.

Prefix bins are doubling, in 1024-token units: ``<1k, 1-2k, 2-4k, 4-8k, 8-16k, 16-32k, 32-64k,
64-128k, 128-256k, >256k`` (the same ``prefix_tokens`` / ``newly_append_tokens`` accounting used
by ``prefix_append_distribution`` and ``token_length_distribution``, so the numbers reconcile).

Run with the standard trace-db CLI (``--db`` | ``-i/--input`` | ``-o/--output-dir``).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

EXP_DIR = Path(__file__).resolve().parent
REPO_ROOT = EXP_DIR.parents[2]  # append_by_prefix_bin -> llm_generation -> artifacts -> repo root
sys.path.insert(0, str(REPO_ROOT / "artifacts" / "utils"))

import md_table  # noqa: E402  (gfm_table / section_tables for the web detail page)
import trace_db  # noqa: E402

PROVIDERS = ("claude", "codex")
PERCENTILES = (50, 90, 99)
_K = 1024
# (label, lo_inclusive, hi_exclusive) over prefix_tokens; doubling bins, stop at 256k.
BINS = [
    ("$<$1k", 0, 1 * _K),
    ("1--2k", 1 * _K, 2 * _K),
    ("2--4k", 2 * _K, 4 * _K),
    ("4--8k", 4 * _K, 8 * _K),
    ("8--16k", 8 * _K, 16 * _K),
    ("16--32k", 16 * _K, 32 * _K),
    ("32--64k", 32 * _K, 64 * _K),
    ("64--128k", 64 * _K, 128 * _K),
    ("128--256k", 128 * _K, 256 * _K),
    ("$>$256k", 256 * _K, float("inf")),
]


def collect(con) -> dict[str, dict[str, dict[str, float]]]:
    """Return ``{provider: {bin_label: {n, avg, p50, p90, p99}}}``."""
    appends: dict[tuple[str, str], list[int]] = {(p, b[0]): [] for p in PROVIDERS for b in BINS}
    for provider, prefix, append in con.execute(
        "SELECT provider, prefix_tokens, newly_append_tokens FROM rounds "
        "WHERE provider IN ('claude', 'codex')"
    ).fetchall():
        prefix = int(prefix or 0)
        append = int(append or 0)
        for label, lo, hi in BINS:
            if lo <= prefix < hi:
                appends[(provider, label)].append(append)
                break

    out: dict[str, dict[str, dict[str, float]]] = {p: {} for p in PROVIDERS}
    for provider in PROVIDERS:
        for label, _lo, _hi in BINS:
            arr = np.asarray(appends[(provider, label)], dtype=float)
            row = {"n": int(arr.size), "avg": float(arr.mean()) if arr.size else 0.0}
            pcts = np.percentile(arr, PERCENTILES) if arr.size else [0] * len(PERCENTILES)
            row.update({f"p{q}": float(v) for q, v in zip(PERCENTILES, pcts)})
            out[provider][label] = row
    return out


def toks(x: float) -> str:
    if x >= 1000:
        return f"{x / 1000:.1f}K"
    return f"{x:.0f}"


def render_tex(data: dict[str, dict[str, dict[str, float]]]) -> str:
    lines = [
        "% AUTO-GENERATED by artifacts/llm_generation/append_by_prefix_bin/analyze.py -- do not",
        "% edit by hand; re-run on the trace to refresh.",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Append tokens per step, conditioned on the number of prefix tokens, "
        "for each provider. Prefix bins are doubling, in 1024-token units; \\emph{Steps} "
        "is the number of steps in the bin.}",
        "\\label{tab:append_by_prefix}",
        "\\small",
        "\\setlength{\\tabcolsep}{5pt}",
        "\\renewcommand{\\arraystretch}{1.15}",
        "\\begin{tabular}{l r r r r r}",
        "\\toprule",
        "\\textbf{Prefix} & \\textbf{Steps} & \\textbf{Avg} & \\textbf{P50} & \\textbf{P90} "
        "& \\textbf{P99} \\\\",
        "\\midrule",
    ]
    for pi, provider in enumerate(PROVIDERS):
        if pi:
            lines.append("\\addlinespace")
        lines.append(f"\\multicolumn{{6}}{{@{{}}l}}{{\\emph{{{provider.capitalize()}}}}} \\\\")
        for label, _lo, _hi in BINS:
            s = data[provider][label]
            cell = (lambda k: "--" if s["n"] == 0 else toks(s[k]))
            lines.append(
                f"\\quad {label} & {s['n']:,} & {cell('avg')} & {cell('p50')} "
                f"& {cell('p90')} & {cell('p99')} \\\\"
            )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines) + "\n"


def render_md(data: dict[str, dict[str, dict[str, float]]]) -> str:
    """GFM mirror of :func:`render_tex` for the web detail page (table only — the page adds a caption)."""
    headers = ["Prefix", "Steps", "Avg", "P50", "P90", "P99"]
    sections: list[tuple[str, list[list[str]]]] = []
    for provider in PROVIDERS:
        rows: list[list[str]] = []
        for label, _lo, _hi in BINS:
            s = data[provider][label]
            plain = label.replace("$", "").replace("--", "-")
            cell = (lambda k: "--" if s["n"] == 0 else toks(s[k]))
            rows.append([plain, f"{s['n']:,}", cell("avg"), cell("p50"), cell("p90"), cell("p99")])
        sections.append((provider.capitalize(), rows))
    return md_table.section_tables(headers, sections, ["l", "r", "r", "r", "r", "r"])


def render_headline(data: dict[str, dict[str, dict[str, float]]]) -> list[dict[str, str]]:
    """The 2–4 most important numbers for the Overview gallery card (label + formatted value).

    Derived from the same per-provider stats as the table so the card never drifts: the cold-start
    vs warmed median append (the dominant provider's p50 in the named bin), and the busiest bin.
    Consumed by web/scripts/build-payload.mjs (aggregated into public/data/headlines.json by slug).
    """
    cold_label = BINS[0][0]  # "<1k" -- cold start, no cache
    warm_label = "64--128k"  # first bin past 64k -- well-warmed prefix

    def busiest_p50(label: str) -> dict[str, float]:
        """The named bin's row from whichever provider logged the most steps there."""
        return max((data[p][label] for p in PROVIDERS), key=lambda s: s["n"])

    cold = busiest_p50(cold_label)
    warm = busiest_p50(warm_label)

    # Busiest prefix bin overall, across providers and bins (by step count).
    top_provider, top_label, top_row = max(
        ((p, label, data[p][label]) for p in PROVIDERS for label, _lo, _hi in BINS),
        key=lambda t: t[2]["n"],
    )
    top_plain = top_label.replace("$", "").replace("--", "-")

    return [
        {"label": "Median append, <1k prefix", "value": toks(cold["p50"])},
        {"label": "Median append, >64k prefix", "value": toks(warm["p50"])},
        {"label": "Busiest prefix bin", "value": f"{top_plain} ({top_row['n']:,} steps)"},
    ]


def render_stdout(data: dict[str, dict[str, dict[str, float]]]) -> str:
    out: list[str] = []
    for provider in PROVIDERS:
        out.append(f"[{provider}]")
        out.append(f"  {'prefix':10s} {'n':>9s} {'avg':>9s} {'p50':>9s} {'p90':>9s} {'p99':>9s}")
        for label, _lo, _hi in BINS:
            s = data[provider][label]
            plain = label.replace("$", "").replace("--", "-")
            cell = (lambda k: "--" if s["n"] == 0 else toks(s[k]))
            out.append(
                f"  {plain:10s} {s['n']:>9,d} {cell('avg'):>9s} {cell('p50'):>9s} "
                f"{cell('p90'):>9s} {cell('p99'):>9s}"
            )
        out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    trace_db.add_db_args(parser, default_output_dir=EXP_DIR)
    args = parser.parse_args()

    con = trace_db.open_from_args(args)
    try:
        data = collect(con)
    finally:
        con.close()

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    tex_path = out_dir / "append_by_prefix_bin.tex"
    tex_path.write_text(render_tex(data), encoding="utf-8")
    md_path = out_dir / "append_by_prefix_bin.md"
    md_path.write_text(render_md(data), encoding="utf-8")
    headline_path = out_dir / "headline.json"
    headline_path.write_text(json.dumps(render_headline(data), indent=2) + "\n", encoding="utf-8")

    print(render_stdout(data))
    print(f"Wrote {tex_path}, {md_path} and {headline_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
